//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_TASK3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer_info
    {
       
        public int customer_id { get; set; }
        [Display(Name ="First Name")]
        [Required (ErrorMessage = "enter first name")]
        [StringLength(12, ErrorMessage = "max=12 char")]
        public string first_name { get; set; }
        [Display(Name = "Last Name")]
        [StringLength(12, ErrorMessage = "max=12 char")]
        [Required(ErrorMessage = "enter last_name")]

        public string last_name { get; set; }
        [Display(Name = "E_mail")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "enter email")]
        [RegularExpression(@"\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b")]
        public string email { get; set; }
        [Display(Name = "Number")]
        [Required(ErrorMessage = "enter your num")]
        [RegularExpression(@"^0(77|78|79)\d{7}$")]

        public string phone { get; set; }
        [Display(Name = "Age")]
        [Required(ErrorMessage = "enter your age")]
        [Range(18, 50,ErrorMessage ="out range")]
        public int age { get; set; }
        [Required ]
        [StringLength (10,ErrorMessage ="max=10 char")]
        [Display(Name = "JOB")]
        public string job_title { get; set; }
        [Required]
        [Display(Name = "Gender")]
        public bool gender { get; set; }
    }
}
